import React from "react";
import PresaleGridCard from "./PresaleGridCard";
import { PresaleType } from "@/types";

export default function PresaleGrid() {
  const presales: PresaleType[] = [
    {
      id: 1,
      banner: "interworld/interworld-banner.webp",
      logo: "interworld/interworld-logo.webp",
      networkLogo: "interworld/abey.webp",
      typeImage: "/interworld/2.svg",
      title: "InterWorld Metaverse Presale #1",
      type: "Presale",
      maxBuy: 50000,
      status: "finalized",
      progress: 100,
      tags: ["KYC+", "AUDIT"],
      target: 1000000,
      raised: 1000000,
      softcap: 300000,
      hardcap: "1M",
      rate: "2ITW",
      lock: "Manual",
      tabs: [
        {
          id: 1,
          name: "About",
          content:
            "InterWorld is an upcoming metaverse built on the Abey blockchain with UE5 graphics. The teaser concert features @whoisdvrko's performance in our alpha launch.",
          ytVideo: "https://youtu.be/ijg1s_bjf2Q",
        },
        {
          id: 2,
          name: "Sale",
          network: "abby",
          presaleAddress: "0xD644BdAF8627118d723168e5083864c041CdC2d5",
          tokenName: "InterWorld Token",
          tokenSymbol: "ITW",
          totalSupply: 3681541.1,
          tokensForPresale: 2000000,
          softcap: 300000,
          hardcap: 1000000,
          unusedTokens: "Refund",
          presaleStartTime: "2024-02-14 13:00",
          presaleEndTime: "2024-02-28 13:00",
          liquidityPercent: "Manual Listing",
          tokensReleasedOnLaunch: "8",
          vestingDelay: 30,
          VestingTimePeriod: 30,
          vestingReleasePerTimePeriod: "8",
        },
        {
          id: 3,
          name: "Tokenomics",
          presale: 54.3251,
          unlocked: 45.6749,
          initialMarketCap: 0,
          circulatingMarketCap: 0,
          fdvMarketCap: 0,
        },
        {
          id: 4,
          name: "Locks",
          tokenLocks: 0,
          liquidityLocks: 0,
        },
        {
          id: 5,
          name: "Team",
          members: [
            {
              name: "Interworld",
              title: "Owner",
              twitter: "https://twitter.com/interworld_io",
            },
          ],
        },
      ],
      stats: [
        {
          status: "finalized",
          minimumBuy: "50",
          maxiumumBuy: "50",
          presaleRate: "2ITW",
          listingRate: "2ITW",
          totalContributors: 1272,
          avgContribution: 78616352,
          myContribution: 0,
          myReservedTokens: 0,
          tokenAddress: "0x64F7e4B5B48654c45476ADbc7800a78D3f577C8d",
        },
      ],
      updates: [
        {
          id: 1,
          dateFrom: "3 months ago",
          content:
            "If you need assets on Abey - 1. Bridge USDT on XPlus (https://x.plus) 2. Or purchase ABEY on LBank (https://lbank.com/trade/abey_usdt) then sell on XSwap (https://xswap.com)",
        },
      ],
    },
    {
      id: 2,
      banner: "interworld/interworld-banner.webp",
      logo: "interworld/interworld-logo.webp",
      networkLogo: "interworld/abey.webp",
      typeImage: "/interworld/2.svg",
      title: "InterWorld Metaverse Presale #1",
      type: "Presale",
      maxBuy: 50000,
      status: "finalized",
      progress: 100,
      tags: ["KYC+", "AUDIT"],
      target: 1000000,
      raised: 1000000,
      softcap: 300000,
      hardcap: "1M",
      rate: "2ITW",
      lock: "Manual",
      tabs: [
        {
          id: 1,
          name: "About",
          content:
            "InterWorld is an upcoming metaverse built on the Abey blockchain with UE5 graphics. The teaser concert features @whoisdvrko's performance in our alpha launch.",
          ytVideo: "https://youtu.be/ijg1s_bjf2Q",
        },
        {
          id: 2,
          name: "Sale",
          network: "abby",
          presaleAddress: "0xD644BdAF8627118d723168e5083864c041CdC2d5",
          tokenName: "InterWorld Token",
          tokenSymbol: "ITW",
          totalSupply: 3681541.1,
          tokensForPresale: 2000000,
          softcap: 300000,
          hardcap: 1000000,
          unusedTokens: "Refund",
          presaleStartTime: "2024-02-14 13:00",
          presaleEndTime: "2024-02-28 13:00",
          liquidityPercent: "Manual Listing",
          tokensReleasedOnLaunch: "8",
          vestingDelay: 30,
          VestingTimePeriod: 30,
          vestingReleasePerTimePeriod: "8",
        },
        {
          id: 3,
          name: "Tokenomics",
          presale: 54.3251,
          unlocked: 45.6749,
          initialMarketCap: 0,
          circulatingMarketCap: 0,
          fdvMarketCap: 0,
        },
        {
          id: 4,
          name: "Locks",
          tokenLocks: 0,
          liquidityLocks: 0,
        },
        {
          id: 5,
          name: "Team",
          members: [
            {
              name: "Interworld",
              title: "Owner",
              twitter: "https://twitter.com/interworld_io",
            },
          ],
        },
      ],
      stats: [
        {
          status: "finalized",
          minimumBuy: "50",
          maxiumumBuy: "50",
          presaleRate: "2ITW",
          listingRate: "2ITW",
          totalContributors: 1272,
          avgContribution: 78616352,
          myContribution: 0,
          myReservedTokens: 0,
          tokenAddress: "0x64F7e4B5B48654c45476ADbc7800a78D3f577C8d",
        },
      ],
      updates: [
        {
          id: 1,
          dateFrom: "3 months ago",
          content:
            "If you need assets on Abey - 1. Bridge USDT on XPlus (https://x.plus) 2. Or purchase ABEY on LBank (https://lbank.com/trade/abey_usdt) then sell on XSwap (https://xswap.com)",
        },
      ],
    },
    {
      id: 3,
      banner: "interworld/interworld-banner.webp",
      logo: "interworld/interworld-logo.webp",
      networkLogo: "interworld/abey.webp",
      typeImage: "/interworld/2.svg",
      title: "InterWorld Metaverse Presale #1",
      type: "Presale",
      maxBuy: 50000,
      status: "finalized",
      progress: 100,
      tags: ["KYC+", "AUDIT"],
      target: 1000000,
      raised: 1000000,
      softcap: 300000,
      hardcap: "1M",
      rate: "2ITW",
      lock: "Manual",
      tabs: [
        {
          id: 1,
          name: "About",
          content:
            "InterWorld is an upcoming metaverse built on the Abey blockchain with UE5 graphics. The teaser concert features @whoisdvrko's performance in our alpha launch.",
          ytVideo: "https://youtu.be/ijg1s_bjf2Q",
        },
        {
          id: 2,
          name: "Sale",
          network: "abby",
          presaleAddress: "0xD644BdAF8627118d723168e5083864c041CdC2d5",
          tokenName: "InterWorld Token",
          tokenSymbol: "ITW",
          totalSupply: 3681541.1,
          tokensForPresale: 2000000,
          softcap: 300000,
          hardcap: 1000000,
          unusedTokens: "Refund",
          presaleStartTime: "2024-02-14 13:00",
          presaleEndTime: "2024-02-28 13:00",
          liquidityPercent: "Manual Listing",
          tokensReleasedOnLaunch: "8",
          vestingDelay: 30,
          VestingTimePeriod: 30,
          vestingReleasePerTimePeriod: "8",
        },
        {
          id: 3,
          name: "Tokenomics",
          presale: 54.3251,
          unlocked: 45.6749,
          initialMarketCap: 0,
          circulatingMarketCap: 0,
          fdvMarketCap: 0,
        },
        {
          id: 4,
          name: "Locks",
          tokenLocks: 0,
          liquidityLocks: 0,
        },
        {
          id: 5,
          name: "Team",
          members: [
            {
              name: "Interworld",
              title: "Owner",
              twitter: "https://twitter.com/interworld_io",
            },
          ],
        },
      ],
      stats: [
        {
          status: "finalized",
          minimumBuy: "50",
          maxiumumBuy: "50",
          presaleRate: "2ITW",
          listingRate: "2ITW",
          totalContributors: 1272,
          avgContribution: 78616352,
          myContribution: 0,
          myReservedTokens: 0,
          tokenAddress: "0x64F7e4B5B48654c45476ADbc7800a78D3f577C8d",
        },
      ],
      updates: [
        {
          id: 1,
          dateFrom: "3 months ago",
          content:
            "If you need assets on Abey - 1. Bridge USDT on XPlus (https://x.plus) 2. Or purchase ABEY on LBank (https://lbank.com/trade/abey_usdt) then sell on XSwap (https://xswap.com)",
        },
      ],
    },
    {
      id: 4,
      banner: "interworld/interworld-banner.webp",
      logo: "interworld/interworld-logo.webp",
      networkLogo: "interworld/abey.webp",
      typeImage: "/interworld/2.svg",
      title: "InterWorld Metaverse Presale #1",
      type: "Presale",
      maxBuy: 50000,
      status: "finalized",
      progress: 100,
      tags: ["KYC+", "AUDIT"],
      target: 1000000,
      raised: 1000000,
      softcap: 300000,
      hardcap: "1M",
      rate: "2ITW",
      lock: "Manual",
      tabs: [
        {
          id: 1,
          name: "About",
          content:
            "InterWorld is an upcoming metaverse built on the Abey blockchain with UE5 graphics. The teaser concert features @whoisdvrko's performance in our alpha launch.",
          ytVideo: "https://youtu.be/ijg1s_bjf2Q",
        },
        {
          id: 2,
          name: "Sale",
          network: "abby",
          presaleAddress: "0xD644BdAF8627118d723168e5083864c041CdC2d5",
          tokenName: "InterWorld Token",
          tokenSymbol: "ITW",
          totalSupply: 3681541.1,
          tokensForPresale: 2000000,
          softcap: 300000,
          hardcap: 1000000,
          unusedTokens: "Refund",
          presaleStartTime: "2024-02-14 13:00",
          presaleEndTime: "2024-02-28 13:00",
          liquidityPercent: "Manual Listing",
          tokensReleasedOnLaunch: "8",
          vestingDelay: 30,
          VestingTimePeriod: 30,
          vestingReleasePerTimePeriod: "8",
        },
        {
          id: 3,
          name: "Tokenomics",
          presale: 54.3251,
          unlocked: 45.6749,
          initialMarketCap: 0,
          circulatingMarketCap: 0,
          fdvMarketCap: 0,
        },
        {
          id: 4,
          name: "Locks",
          tokenLocks: 0,
          liquidityLocks: 0,
        },
        {
          id: 5,
          name: "Team",
          members: [
            {
              name: "Interworld",
              title: "Owner",
              twitter: "https://twitter.com/interworld_io",
            },
          ],
        },
      ],
      stats: [
        {
          status: "finalized",
          minimumBuy: "50",
          maxiumumBuy: "50",
          presaleRate: "2ITW",
          listingRate: "2ITW",
          totalContributors: 1272,
          avgContribution: 78616352,
          myContribution: 0,
          myReservedTokens: 0,
          tokenAddress: "0x64F7e4B5B48654c45476ADbc7800a78D3f577C8d",
        },
      ],
      updates: [
        {
          id: 1,
          dateFrom: "3 months ago",
          content:
            "If you need assets on Abey - 1. Bridge USDT on XPlus (https://x.plus) 2. Or purchase ABEY on LBank (https://lbank.com/trade/abey_usdt) then sell on XSwap (https://xswap.com)",
        },
      ],
    },
  ];

  return (
    <div className="w-full grid grid-cols-4 mt-12 gap-4">
      {presales.map((presale) => (
        <div key={presale.id}>
          <PresaleGridCard presale={presale} />
        </div>
      ))}
    </div>
  );
}
